# Generated by Django 4.1.3 on 2022-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='education',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Light', 'Light')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='User_file/Profile_picture/'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='theme',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Light', 'Light')], max_length=10, null=True),
        ),
    ]
