# Generated by Django 4.1.3 on 2022-11-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='presentation',
        ),
        migrations.CreateModel(
            name='Staged_presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aba_app.presentation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aba_app.stage')),
            ],
        ),
    ]
