# Generated by Django 4.1.3 on 2022-11-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0002_remove_stage_presentation_staged_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='rub_owner',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stage_owner',
        ),
        migrations.RemoveField(
            model_name='staged_presentation',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='staged_presentation',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Staged_presentation',
        ),
    ]
