# Generated by Django 4.1.3 on 2022-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0002_questiontable_response_usersetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='presentation',
        ),
        migrations.AddField(
            model_name='stage',
            name='presentation',
            field=models.ManyToManyField(to='aba_app.presentation'),
        ),
    ]
