# Generated by Django 4.1.3 on 2022-11-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0003_remove_stage_presentation_stage_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Stage_image',
            field=models.ImageField(blank=True, null=True, upload_to='stage_images/'),
        ),
    ]
