# Generated by Django 4.1.3 on 2022-11-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0007_presentation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontable',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiontable',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
