# Generated by Django 4.1.3 on 2022-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0008_alter_questiontable_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.CharField(choices=[('APPROVE', 'APPROVED'), ('DECLINE', 'DECLINED'), ('UNAPPROVED', 'UNAPPROVED')], max_length=15),
        ),
    ]
