# Generated by Django 4.1.3 on 2022-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0011_staged_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='staged_presentation',
            name='presentation',
        ),
        migrations.AddField(
            model_name='staged_presentation',
            name='presentation',
            field=models.ManyToManyField(blank=True, null=True, to='aba_app.presentation'),
        ),
    ]
