# Generated by Django 4.1.3 on 2022-11-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0013_presentation_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staged_presentation',
            name='presentation',
        ),
        migrations.AddField(
            model_name='staged_presentation',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aba_app.presentation'),
        ),
    ]
