# Generated by Django 4.1.3 on 2022-11-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0014_remove_staged_presentation_presentation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staged_presentation',
            name='stage',
        ),
    ]
