# Generated by Django 4.1.3 on 2022-11-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0015_remove_staged_presentation_stage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staged_presentation',
        ),
    ]
