# Generated by Django 4.1.3 on 2022-11-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0016_delete_staged_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Declined', 'DECLINED'), ('Unapproved', 'UNAPPROVED')], default=('Unapproved', 'UNAPPROVED'), max_length=15),
        ),
    ]
