# Generated by Django 4.1.3 on 2022-11-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aba_app', '0017_alter_presentation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Declined'), ('3', 'Unapproved')], default=('3', 'Unapproved'), max_length=15),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pres_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pres_owner',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_owner',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
