# Generated by Django 4.1.3 on 2022-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0018_presentation_user_stage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='aba_app.questiontable'),
        ),
    ]
