# Generated by Django 4.1.3 on 2022-11-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0019_presentation_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='questiontable',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aba_app.presentation'),
        ),
        migrations.AddField(
            model_name='response',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aba_app.presentation'),
        ),
    ]
