# Generated by Django 4.1.3 on 2022-11-21 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aba_app', '0028_alter_evaluation_evalution_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='user',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pres_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
