# Generated by Django 4.1.3 on 2022-11-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0029_remove_presentation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentation',
            old_name='pres_owner',
            new_name='owner',
        ),
    ]
