# Generated by Django 4.1.3 on 2022-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0030_rename_pres_owner_presentation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.CharField(choices=[('1', 'Approved'), ('2', 'Declined'), ('3', 'Unapproved')], default=('2', 'Declined'), max_length=15),
        ),
    ]
