# Generated by Django 4.1.3 on 2022-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0031_alter_presentation_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
