# Generated by Django 4.1.3 on 2022-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0035_alter_evaluation_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria',
            new_name='criteria1',
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='criteria',
            name='criteria3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
