# Generated by Django 4.1.3 on 2022-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0036_rename_criteria_criteria_criteria1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='criteria_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='criteria',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
