# Generated by Django 4.1.3 on 2022-11-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0037_criteria_criteria_name_criteria_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criteria',
            old_name='criteria1',
            new_name='criteria',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='criteria2',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='criteria3',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='criteria_name',
        ),
        migrations.RemoveField(
            model_name='criteria',
            name='type',
        ),
    ]
