# Generated by Django 4.1.3 on 2022-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0041_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review3',
            field=models.IntegerField(null=True),
        ),
    ]
