# Generated by Django 4.1.3 on 2022-12-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0045_presentation_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_owner',
        ),
    ]
