# Generated by Django 4.1.3 on 2022-12-04 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aba_app', '0046_remove_stage_stage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionflow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='evaluation_owner',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans_owner',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ques_owner',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Declined', 'Declined'), ('Unapproved', 'Unapproved')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerFlow',
        ),
        migrations.DeleteModel(
            name='QuestionFlow',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aba_app.question'),
        ),
    ]
