# Generated by Django 4.1.3 on 2022-12-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0049_alter_presentation_pres_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pres_file',
            field=models.FileField(blank=True, default='/media/stage_images/logo.png', max_length=250, null=True, upload_to='presentation_files/'),
        ),
    ]
