# Generated by Django 4.1.3 on 2022-12-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0051_alter_presentation_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='pres_file',
            field=models.FileField(blank=True, default='/media/stage_images/logo.png', null=True, upload_to='presentation_files/'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='category',
            field=models.CharField(blank=True, choices=[('Lecture halls', 'Lecture halls'), ('Opera houses', 'Opera houses'), ('Church', 'Church'), ('Concert halls', 'Concert halls'), ('Theaters', 'Theaters'), ('Playhouses.', 'Playhouses'), ('All purpose', 'All purpose'), ('Other', 'Other')], max_length=60, null=True),
        ),
    ]
