# Generated by Django 4.1.3 on 2022-12-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0052_alter_presentation_pres_file_alter_stage_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
