# Generated by Django 4.1.4 on 2022-12-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0053_delete_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
