# Generated by Django 4.1.4 on 2022-12-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0054_alter_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='openEndedAnswer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='openEndedQuestion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
