# Generated by Django 4.1.4 on 2022-12-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0055_answer_openendedanswer_question_openendedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='openEndedQuestion',
        ),
    ]
