# Generated by Django 4.1.4 on 2022-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba_app', '0063_rename_state_bestpresentation_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='members',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
